#!/bin/sh
# ---------------------------------------------------------------------------
# env-to-config.sh — turn .env into the config.js the page actually loads.
#
#   sh tools/env-to-config.sh
#
# The game is plain HTML and JavaScript served as static files, so the browser
# has no way to read .env itself. This script is the bridge: .env is where you
# keep the settings, config.js is what index.html loads. Re-run it whenever
# .env changes.
#
# Both .env and config.js are gitignored. This script is not — it contains no
# secrets, only the wiring.
# ---------------------------------------------------------------------------
set -eu

cd "$(dirname "$0")/.."

ENV_FILE=".env"
OUT_FILE="config.js"

if [ ! -f "$ENV_FILE" ]; then
  echo "error: no $ENV_FILE found." >&2
  echo "       cp .env.example .env    then fill in your Supabase details." >&2
  exit 1
fi

# Read one KEY=VALUE out of .env. Deliberately parsed rather than sourced: a
# backtick or $(...) in a pasted key would otherwise be executed by the shell.
# Later definitions win, and surrounding quotes are stripped.
get_var() {
  sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*//p" "$ENV_FILE" \
    | tail -n 1 \
    | sed -e 's/[[:space:]]*$//' \
          -e 's/^"\(.*\)"$/\1/' \
          -e "s/^'\(.*\)'\$/\1/"
}

# Escape for embedding in a single-quoted JavaScript string.
js_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e "s/'/\\\\'/g"
}

URL=$(get_var SUPABASE_URL)
KEY=$(get_var SUPABASE_ANON_KEY)

if [ -z "$URL" ] || [ -z "$KEY" ]; then
  echo "error: SUPABASE_URL and SUPABASE_ANON_KEY must both be set in $ENV_FILE" >&2
  exit 1
fi

case "$URL" in
  *YOUR-PROJECT-REF*|*YOUR-ANON*)
    echo "error: $ENV_FILE still has the placeholder values from .env.example." >&2
    exit 1 ;;
esac

# The service_role key carries "role":"service_role" in its payload. Shipping it
# to a browser would bypass Row Level Security entirely, so refuse outright.
if printf '%s' "$KEY" | cut -d. -f2 | tr '_-' '/+' | base64 -d 2>/dev/null | grep -q 'service_role'; then
  echo "error: that looks like the service_role key, not the anon key." >&2
  echo "       It bypasses Row Level Security and must never reach a browser." >&2
  echo "       Use Project Settings -> API -> anon / public instead." >&2
  exit 1
fi

cat > "$OUT_FILE" <<EOF
/* Generated by tools/env-to-config.sh from .env — do not edit by hand.
   Not committed to the repository; see .env.example. */
window.BAYANIHAN_CONFIG = {
  supabaseUrl     : '$(js_escape "$URL")',
  supabaseAnonKey : '$(js_escape "$KEY")'
};
EOF

echo "wrote $OUT_FILE from $ENV_FILE"
echo "  url: $URL"
echo "  key: $(printf '%s' "$KEY" | cut -c1-12)... (${#KEY} chars)"
